name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # adapt to your version

      - name: Install dependencies
        run: |
          pip install -e .
          pip install sphinx  
          pip install furo 

      - name: Build Sphinx docs
        run: |
          make -C docs/ html

      - name: Deploy to neuroptimiser.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: neuroptimiser/neuroptimiser.github.io
          publish_dir: neuroptimiser/docs/_build/html
          publish_branch: main
