name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - gh-pages 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Deploy to neuroptimiser.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: neuroptimiser/neuroptimiser.github.io
          publish_dir: .
          publish_branch: main